config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get 'favorite'
    end
    resource :relationships, only: [:create, :destroy]
    get 'following' => 'relationships#following', as: 'following'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :messages, only: [:create]
  resources :rooms, only:[:create, :show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


	belongs_to :user
	has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  #すでにお気に入りされているかどうかを判定
  #user_id: user.id user_idという箱に user.idが入っていると解釈
  #user.idには@user.id,current_user.idとかが入って使われる

  is_impressionable counter_cache: true
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	validates :comment, presence: true
	belongs_to :user
	belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
	# 複数の参加者一人一人にユーザーIDとルーム
	belongs_to :user
	belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :book
	belongs_to :user

	validates_uniqueness_of :book_id, scope: :user_id
	#本一つにユーザーは一人だけ（複数回のいいねを防ぐ）
end

app/models/message.rb
class Message < ApplicationRecord
	# 空白のメッセージは送れない
	validates :content, presence:true, length: { maximum: 140 }
	# たくさんのメッセージそれぞれにユーザーIDとルームのID
	belongs_to :user
	belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true


end

app/models/room.rb
class Room < ApplicationRecord
	# 一つのルームにたくさんのメッセージ
	has_many :messages, dependent: :destroy
	# 一つのルームに複数（二人）の
	has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
  # アソシエーション（関連づけ）
  has_many :books, dependent: :destroy
  # コメント機能
  has_many :book_comments, dependent: :destroy
  # いいね機能
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  # フォロー機能
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  # DM機能
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy


  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following.include?(user)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    #一週間でいいねの多い順で投稿を表示
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
    # {|a,b|a.to_i <=> b.to_i}だと昇順になる
    #今回で言うといいねの少ない順
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created user successfully.'
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.new
    @book = Book.find(params[:id])
    impressionist(@book)
    @user = @book.user
    @book_comment = BookComment.new

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render :edit
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updateed user successfully.'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end

	def about
	end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :authenticate_user!

	def create
		@room = Room.create
		@entry1 = Entry.create(user_id: current_user.id, room_id: @room.id)
		
		@entry2 = Entry.create(join_room_params)
		redirect_to room_path(@room.id)
	end

	def show
		@room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
	end

	private

	def join_room_params
   params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def index
    @users = User.all
    @book = Book.new
	end

	def show
		@user = User.find(params[:id])
		# DM機能
		@currentUserEntry = Entry.where(user_id: current_user.id)
		@userEntry = Entry.where(user_id: @user.id)
		unless @user.id == current_user.id
			# 自分と他ユーザーの持つルームIDをそれぞれ比べる
			@currentUserEntry.each do |cu|
				@userEntry.each do |u|
					# 同じIDを持っていた時
					if cu.room_id == u.room_id then
						# if ~ true => elseの状況を作るための定義
						@haveRoom = true
						# 同じIDをIDとしてページ遷移するときに使う
						@roomId = cu.room_id
					end
				end
			end
			# 同じIDを持ってなかったら
			# 意味はわかる
			unless @haveRoom # = trueってこと？
				@room = Room.new
				@entry = Entry.new
			end
		end
		@book = Book.new
		@books = @user.books
	end

	def edit
		@user = User.find(params[:id])
		if @user == current_user
    	render "edit"
		else
      redirect_to user_path(current_user.id)
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
		else
			render :edit
		end
	end

	def favorite
		@user = User.find_by(id: params[:id])
  	@favorites = Favorite.where(user_id: @user.id)
	end


	private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_comment.html.erb
<table>
	<tbody>
		<div class="comments">
			<% book.book_comments.each do |book_comment| %>
				<tr>
					<td>
						<p>
							<%= attachment_image_tag book_comment.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
						</p>
						<%= link_to user_path(book.user.id)do %>
						<%= book_comment.user.name %>
						<% end %>
					</td>
					<td>
						<p><%= book_comment.comment %></p>
					</td>
					<td>
						<% if book_comment.user == current_user %>
						<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</div>
	</tbody>
</table>

app/views/books/_detail.html.erb
<table class="table">
	<tbody>
		<tr>
			<td>
				<%= link_to user_path(book.user.id)do %>
				<%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %></br>
				<%= book.user.name %>
				<% end %>
			</td>
			<td>
				<%= link_to book.title, book_path(book.id) %>
			</td>
			<td>
				<%= book.body %>
			</td>
			<td class="favorite-<%= @book.id %>">
				<% if book.user == current_user %>
					<%= link_to 'Edit' , edit_book_path(book.id), class:"btn btn-sm btn-success" %>
				<% else %>
					<%= render 'favorites/favorite-btn', book: @book %>
				<% end %>
			</td>
				<% if book.user == current_user %>
			<td>
				<%= link_to 'Destroy' , book_path(book.id), method: :delete, class:"btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？"  %>
			</td>
				<% end %>
			<td class="comment-count">
				<p>コメント件数：<%= book.book_comments.count %></p>
			</td>
			<td>
				<p>PV数：<%= book.impressions_count %></p>
			</td>
		</tr>
	</tbody>
</table>

app/views/books/_form.html.erb
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class:"form-control book_title", id:"book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
		<%= f.text_area :body, class:"form-control book_body", id:"book_body" %>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% books.each do |book| %>
			<tr>
				<td>
					<%= link_to user_path(book.user.id) do %>
					<%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
					<% end %>
				</td>
				<td>
					<%= link_to book.title, book_path(book.id) %>
				</td>
				<td>
					<%= book.body %>
				</td>
				<td class="favorite-<%= book.id %>">
					<%= render 'favorites/favorite-btn', book: book %>
				</td>
				<td>
					<p>コメント数：<%= book.book_comments.count %></p>
				</td>
				<td>
					<p>PV数：<%= book.impressions_count %></p>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
			<div id="error_explanation">
				<%= render 'layouts/errors', book: @book %>
			</div>
			<h1>Editing Book</h1>
			<%= render 'form', book: @book %>
			<%= link_to 'Show', book_path(@book.id), class: "@user.id" %>
			|
			<%= link_to 'Back', books_path, class: "back" %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
	<div id="error_explanation">
		<%= render 'layouts/errors', book: @book %>
  </div>
	<div class="row">
		<div class="col-md-3">
			<h2>User info</h2>
			<%= render 'users/info', user: current_user %>
			<h2 class="mt-3">New book</h2>
			<%= render 'form', book: @book %>
		</div>
		<div class="col-md-8 offset-md-1">
			<h2>Books</h2>
			<%= render 'index', books: @books %>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div id="error_explanation">
		<%= render 'layouts/errors', book: @book %>
  </div>
	<div class="row">
		<div class="col-md-3">
			<h2>User info</h2>
			<%= render 'users/info', user: @book.user %>
			<h2 class="mt-3">New book</h2>
			<%= render 'form', book: Book.new %>
		</div>
		<div class="col-md-8 offset-md-1">
			<h2>Book detail</h2>
			<%= render 'detail', book: @book %>
			<div class="comment-<%= @book.id %>">
				<%= render 'book_comments/comment', book: @book %>
			</div>
			<div class="new-comment">
				<%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
				<%= f.text_area :comment, size: "100x5" %>
				<%= f.submit "送信" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/rooms/show.html.erb
<div class="left-button">
  <%= link_to "ユーザー一覧に戻る", users_path, class:"edit-link" %>
</div>
<h4 class="rooms-title">トークメンバー</h4>
<% @entries.each do |e| %>
  <div class="user-name">
  <strong>
    <%= attachment_image_tag e.user, :profile_image, size: "40x40", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
      <a class="rooms-user-link" href="/users/<%= e.user.id %>">
        <%= e.user.name %>さん
      </a>
  </strong>
  </div>
<% end %>
<hr>
<div class="chats">
  <div class="chat">
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <div class="chat-box">
          <div class="chat-face">
    				<%= attachment_image_tag m.user, :profile_image, size: "40x40", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
          </div>
          <div class="chat-hukidashi"> <strong><%= m.content %></strong> <br>
            <%= m.created_at.strftime("%Y-%m-%d %H:%M")%>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="posts">
    <%= form_with model: @message, local:true do |f| %>
      <%= f.text_field :content, placeholder: "メッセージを入力して下さい" , size: 70, class:"form-text-field" %>
        <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.submit "投稿",class: 'form-submit'%>
    <% end %>
  </div>
</div>

app/views/users/_index.html.erb
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</th>
	</thead>
	<tbody>
	  <% users.each do |user| %>
			<tr>
				<td>
					<%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
				</td>
				<td>
					<%= user.name %>
				</td>
				<td>
					<p>フォロー数：<%= user.following.count %></p>
				</td>
				<td>
					<p>フォロワー数：<%= user.followers.count %></p>
				</td>
				<td>
					<% if current_user != user %>
						<% if current_user.following?(user) %>
							<%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
						<% else %>
							<%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
						<% end %>
					<% end %>
        </td>
				<td>
					<%= link_to 'Show', user_path(user.id), class: "@user.id" %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/users/_info.html.erb
<table class="table">
	<div class="info">
		<div class="image box">
			<%= attachment_image_tag user, :profile_image, size: "100x100", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
		</div>
		<div class="dm box">
			<% unless user.id == current_user.id %>
				<% if (current_user.following? user) && (user.following? current_user) %>
					<% if @haveRoom ==  true %>
						<p>
							<%= link_to room_path(@roomId) do %>
							<i class="far fa-comment fa-3x"></i>
							<% end %>
						</p>
					<% else %>
						<%= form_with model: @room, local:true do |f| %>
							<%= fields_for @entry do |e| %>
								<%= e.hidden_field :user_id, value: user.id %>
							<% end %>
							<%= f.button :type => "submit", style: 'border-style: none; background-color: #fff;' do %>
								<i class="far fa-comment fa-3x"></i>
							<% end %>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
		</div>
	<tbody>
		<tr>
		</tr>
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>follows</th>
			<th><%= link_to user.following.count, user_following_path(user.id) %></th>
		</tr>
		<tr>
			<th>followers</th>
			<th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
		</tr>
		<tr>
			<th>favorite books</th>
			<th class="favorite-count">
				<%= link_to "一覧", favorite_user_path(user.id) %>
				<!--link_to user.favorites.count, favorite_user_path(user.id)-->
				<!-- render "favorites/favorite-count", user: user -->
				<!--自分のページだとうまくいくが他人のページでもいいねの数が変動してしまう-->
			</th>
		</tr>
	</tbody>
</table>
<div class="row">
	<% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
  <% else %>
    <%= link_to edit_user_path(current_user.id), class:"btn btn-outline-secondary btn-block" do %>
		<i class="fas fa-user-cog"></i>
		<% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
			<div id="error_explanation">
				<% if @user.errors.any? %>
					<h2><%= @user.errors.count %> error prohibited this obj from being saved:</h2>
					<ul>
						<% if @user.errors.include?(:name) %>
							<li>
								<%= @user.errors.full_messages_for(:name).first %>
							</li>
						<% end %>
						<% if @user.errors.include?(:introduction) %>
							<li>
								<%= @user.errors.full_messages_for(:introduction).first %>
							</li>
						<% end %>
					</ul>
				<% end %>
			</div>
			<h2>User info</h2>
			<%= form_with model: @user, local:true do |f| %>
				<div class="form-group">
					<label for="userName">Name</label></br>
					<%= f.text_field :name, autofocus: true, class:"formControl name", id:"userName" %>
				</div>
				<div class="form-group">
					<label for="inputImage">Image</label></br>
					<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class:"formControl-fila userImage", id:"user_profile_image" %>
				</div>
				<div class="form-group">
					<label for="user_introduction">Introduction</label></br>
					<%= f.text_area :introduction, class:"form-control introduction", id:"user_introduction" %>
				</div>
				<div class="form-group">
					<input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/favorite.html.erb
<h2>Favorite Books</h2>
<% if @favorites.exists? %>
	<table class="table">
			<thead>
				<tr>
					<th></th>
					<th>title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @user.favorite_books.each do |book| %>
					<tr>
						<td>
							<%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg"%>
						</td>
						<td>
							<%= link_to book.title, book_path(book.id) %>
						</td>
						<td>
							<%= book.body %>
						</td>
						<td class="favorite-<%= book.id %>">
							<%= render 'favorites/favorite-btn', book: book %>
						</td>
						<td>
							<p>コメント数：<%= book.book_comments.count %></p>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
<% else %>
	<p>いいねしている本はありません</p>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
	<div id="error_explanation">
		<%= render 'layouts/errors', book: @book %>
 	</div>
	<div class="row">
		<div class="col-md-3">
			<h2>User info</h2>
			<div class="info">
				<%= render 'info', user: current_user %>
			</div>
			<h2 class="mt-3">New book</h2>
			<%= render 'books/form', book: @book %>
		</div>
		<div class="col-md-8 offset-md-1">
			<h2>Users</h2>
			<%= render 'index', users: @users %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
	<div id="error_explanation">
		<%= render 'layouts/errors', book: @book %>
	</div>
	<div class="row">
		<div class="col-md-3">
			<h2>User info</h2>
			<%= render 'info', user: @user %>
			<h2 class="mt-3">New book</h2>
			<%= render 'books/form', book: @book %>
		</div>
		<div class="col-md-8 offset-md-1">
			<h2>Books</h2>
			<%= render 'books/index', books: @books %>
		</div>
	</div>
</div>