config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get 'favorite'
    end
    resource :relationships, only: [:create, :destroy]
    get 'following' => 'relationships#following', as: 'following'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :messages, only: [:create]
  resources :rooms, only:[:create, :show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


	belongs_to :user
	has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  #すでにお気に入りされているかどうかを判定
  #user_id: user.id user_idという箱に user.idが入っていると解釈
  #user.idには@user.id,current_user.idとかが入って使われる

  is_impressionable counter_cache: true
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	validates :comment, presence: true
	belongs_to :user
	belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
	# 複数の参加者一人一人にユーザーIDとルーム
	belongs_to :user
	belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :book
	belongs_to :user

	validates_uniqueness_of :book_id, scope: :user_id
	#本一つにユーザーは一人だけ（複数回のいいねを防ぐ）
end

app/models/message.rb
class Message < ApplicationRecord
	# 空白のメッセージは送れない
	validates :content, presence:true, length: { maximum: 140 }
	# たくさんのメッセージそれぞれにユーザーIDとルームのID
	belongs_to :user
	belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true


end

app/models/room.rb
class Room < ApplicationRecord
	# 一つのルームにたくさんのメッセージ
	has_many :messages, dependent: :destroy
	# 一つのルームに複数（二人）の
	has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
  # アソシエーション（関連づけ）
  has_many :books, dependent: :destroy
  # コメント機能
  has_many :book_comments, dependent: :destroy
  # いいね機能
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  # フォロー機能
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  # DM機能
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy


  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following.include?(user)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    #一週間でいいねの多い順で投稿を表示
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
    # {|a,b|a.to_i <=> b.to_i}だと昇順になる
    #今回で言うといいねの少ない順
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created user successfully.'
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.new
    @book = Book.find(params[:id])
    impressionist(@book)
    @user = @book.user
    @book_comment = BookComment.new

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render :edit
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updateed user successfully.'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end

	def about
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if book.errors.any? %>
  <h2><%= book.errors.count %> error prohibited this obj from being saved:</h2>
  <ul>
    <% if book.errors.include?(:title) %>
      <li>
        <%= book.errors.full_messages_for(:title).first %>
    <% end %>
      </li>
    <% if book.errors.include?(:body) %>
      <li>
        <%= book.errors.full_messages_for(:body).first %>
    <% end %>
      </li>
  </ul>
  <% end %>

app/views/layouts/_footer.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="mx-auto">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
		<a class="navbar-brand" href="/">
			<span>Bookers</span>
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
			<ul class="navbar-nav ml-auto">
				<% if user_signed_in? %>
					<li>
						<%= link_to 'Home', user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
					</li>
					<li>
						<%= link_to 'Users', users_path, class: 'fas fa-users nav-link text-light' %>
					</li>
					<li>
						<%= link_to 'Books', books_path, class: 'fas fa-book-open nav-link text-light' %>
					</li>
					<li>
						<%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
					</li>
				<% else %>
					<li>
						<a class="fas fa-home nav-link text-light" href="/"><%= "Home" %></a>
					</li>
					<li>
						<%= link_to 'About', home_about_path, class: 'fas fa-link nav-link text-light' %>
					</li>
					<li>
						<%= link_to 'sign up', new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
					</li>
					<li>
						<%= link_to 'login', new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>
<% if user_signed_in? %>
	<%= render 'searches/form' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <main>
      <p id="notice"><%= notice %></p>
    <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>